PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?entity ?label WHERE {
  ?entity rdfs:label ?label .
  FILTER regex(str(?label), "chirurg|bisturi|specillo|scalpello|strumentario|Eutyches", "i")
}
LIMIT 100
