PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?entity ?label ?type WHERE {
  ?entity rdfs:label ?label ;
          a ?type .
  FILTER regex(?label, "domus del chirurgo", "i")
}
