PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?direction ?prop ?other WHERE {
  { <https://w3id.org/arco/resource/Site/341671000c872aa799b1e99ae08ca1e8> ?prop ?other .
    BIND("uscente" AS ?direction) }
  UNION
  { ?other ?prop <https://w3id.org/arco/resource/Site/341671000c872aa799b1e99ae08ca1e8> .
    BIND("entrante" AS ?direction) }
}
ORDER BY ?direction LIMIT 200
